### ISSUE TITLE
Upgrade to Node 5

### ISSUE THREAD

**Issue by rf** [uber-archive/hyperbahn#122]
Questionable:
- probably faster. At least for peer choice there was a clear speed improvement
- Map/Set, probably faster over object/array for applicable work

Pros:
- Support for IRHydra for more better optimizations
- Better supported in the community; especially security upgrades

Cons:
- Supporting TChannel in 2 different node versions
- optimizations for Node 5 may not be applicable / may even slow down  Node 0.10
- needs working heap, core & flamegraph tooling
- cannot use ES2015 features whilst support node0.10

TBD:
- Better heap analysis tooling ?
- Better GC analysis tooling ?

**Comment by aledbf** [comment]
@rf any update on this?
Thanks

**Comment by Raynos** [comment]
We will move hyperbahn to node 4.2;

Not sure when exactly. Getting the tests to pass on node 4.2 should be easy. Deploying and verifying in production will be harder.

**Comment by aledbf** [comment]
@Raynos thank you for the update.

**Comment by sashahilton00** [comment]
@Raynos any update on when hyperbahn will be moved to v4.4.7 (LTS)/v5?

**Comment by Raynos** [comment]
@sashahilton00 

Last I looked at the code, upgrading to 4.x is feasible.

We are still running on node0.10 in production with no plans to update. We are evaluation doing a performance benchmark of 0.10 vs 4.x

**Comment by sashahilton00** [comment]
@Raynos ok, good to know. Any idea on where to start with regards to moving Hyperbahn to node 4 in terms of dependencies of Hyperbahn that need updating? I'm seeing a lot of red when compiling, I guess I'll just start reading traces. Thanks.
