### ISSUE TITLE
Disruption Endpoints

### ISSUE THREAD

**Issue by rf** [uber-archive/hyperbahn#18]
We'd like a set of endpoints for creating disruptions between services:
- block % of traffic 
- delay traffic for n ms
- eject % of instances
- manually trigger circuit breaker (sortof done)
- manually trigger rate limiter
- fake advertise service X as Y

I propose we use the service name `hyperbahn` with thrift endpoints in the `HyperbahnDisruption` service. For example, `HyperbahnDisruption::block_traffic_v1`, `HyperbahnDisruption::delay_traffic_v1`, etc.

**Comment by Raynos** [comment]
Let's make the google doc open and link it in this issue.

**Comment by Raynos** [comment]
Let's also add some blocking thrift/tcurl related issues. To really have thrift related admin endpoints that become part of our on call runbook we need a thrift file solution. Ideally `thriftIdl` integration in tcurl.

I think the rest of the thrift/tcurl story is legit/finished.

**Comment by jcorbin** [comment]
- block % of traffic
delay traffic for n ms
eject % of instances
manually trigger circuit breaker (sortof done)
manually trigger rate limiter
fake advertise service X as Y

**Comment by jcorbin** [comment]
Yes:
- block % of traffic
- delay traffic for n ms
- manually trigger circuit breaker (sortof done)
- manually trigger rate limiter

Instead of:
- eject % of instances
Let's have:
- ignore these particular instances; can then be combined with existing discovery api

Instead of:
- fake advertise service X as Y
Please build:
- a pathological dummy service worker that can advertise as arbitrary service, "Y" in this case

**Comment by rf** [comment]
```
admin block-traffic [integer, 0-100: percent] [serviceName]
admin delay-traffic [integer: ms] [serviceName]
admin ignore-instances [serviceName] [hostPort …] 
```

**Comment by Raynos** [comment]
For each thing we need a "query".
For each thing we need a "do the reverse" or a ttl.

**Comment by rf** [comment]
For doing the reverse I was assuming:
```
admin ignore-traffic foo~~bar~~baz 0
admin ignore-instances foo~~bar~~baz     # i.e. empty set
```
etc
